### ISSUE TITLE
Issues with CoCo, paper and implementation

### ISSUE THREAD

**Issue by iuliatamas** [dedis/prifi_archive#1]
In reference to the paper in papers/anon/coco:
1. In the commitment phase I have to compute Vi_hat = Product of Vi and children's Vj_hats
   The Vis in general are point commitments, so when we say product aka multiplication, what do we mean? In crypto/abstract/group.go we have the prototype for Multiplication on Points as: 
         // Encrypt point p by multiplying with secret s.
     // If p == nil, encrypt the standard base point Base().
     Mul(p Point, s Secret) Point
   However, I here only have points and no secrets. 
2. In the Response phase ri_hat is defined as:
     ri_hat  = ri \* ( sum of children's rj_hats)
   
    I was wondering whether this was supposed to be ri_hat = ri + Sum of children's rj_hats 
    I am asking this because if it is not I could have the root receive/ compute an r0 = r1( r2( r3+r4) + r5(r6+r7) ) and I am not sure how I would go about verifying this cumulative response. 
   
    Also related to this second issue, what are the ri_hats of the leafs defined as? I assumed ri_hat = ri if i is a leaf node.

I will soon commit some code for this as well, as maybe seeing the above in the context of some code is better.

**Comment by jackowitz** [comment]
For the multiplication of Points, is it possible that `Add(a, b Point) Point` does what you want (see `nist/residue.go`)?

**Comment by bford** [comment]
Iulia - Danny is correct; the problem is the current, somewhat inconsistent mixture of additive-group and multiplicative-group terminology, even though they really mean the same thing.  The coco draft, as I currently realize, tends to use multiplicative-group terminology, i.e., with multiplication being the "group operator that combines two points and exponentiation being the operation that applies this operation a scalar (exponent) number of times; the library in contrast uses additive-group terminology, so the "group operator" is called addition, and applying that a scalar number of times is called multiplication.  So whenever the document says exponentiate, that means Mul for the library, and whenever the document says multiply, that means point Add.  Sorry about the confusion. :/

And for part 2, you're absolutely right, it should say ri + ... rather than ri \* ... - that's just a typo in the document.  (Feel free to fix and commit that and any other typos you might find in the latex document, as you find them.)

B

**Comment by iuliatamas** [comment]
Thank you for the answers, all makes perfect sense, so I went ahead with the implementation. You can find now on the coco branch a version that works (at least on the 4 node tree I tested on so far, for one round of messaging :) ).

Regarding the collective signing part of the implementation I have 3 questions:
1. How should I go about using random ciphers for different nodes, and what should I initialize them with. At the moment I have: 
func (sn *SigningNode) Commit() {
    // generate secret and point commitment for this round
    rand := abstract.HashStream(sn.suite, []byte(sn.Name()), nil) // change me

here I just generate a random cipher per Commit round per node, intialized with the host's name, for lack of a better idea of what to put in
1. Currently I am initializing the root node with knowledge of all other nodes' Public Keys. How should the root actually get this knowledge?
2. I think I need some advice on integrating ElGamal in general. For now I made the challenge c depend only on the root's V_hat. Because the ElGamal signing phases are split across rounds (aka, the root needs to get the product of the v's from its descendants before it can create the challenge) I wasn't sure how I would use a function like the one in crypto/anon/sig.go, which although nice and good, does everything in one function. 

Thanks

**Comment by bford** [comment]
Awesome, excellent work!!  Finally had a chance to look over the code; I'm attaching a number of comments in-line to the code.  Answers to your two questions above:

1: For now just assume that the knowledge of all nodes' public keys comes in a publicly known and agreed-upon configuration known by everyone, e.g., the same configuration state that defines the tree structure among the nodes.  If you want to make this concrete, you could define a JSON or TOML config file format defining the tree including all nodes' public keys, and take a cryptographic hash of that config file as the "identity" of the collective that's going to be doing the signing.  But this isn't critical; don't spend any time worrying about this for now - just do whatever is most expedient in the test framework.
1. For signature correctness and unforgeability, I believe it's fine to have the challenge c depend only on the root's V_hat, provided that V_hat is a composition of the commits of all the nodes in the network.  If the root were to (for example) leave out some child nodes' commitments, it simply wouldn't be able to produce a valid final top-level signature because the final top-level response (r_hat) would fail to correspond to both the committed V_hat and the top-level aggregate public key (K_hat in the notes I suggested).

Cheers
Bryan
