### ISSUE TITLE
Time Stamping general questions

### ISSUE THREAD

**Issue by iuliatamas** [dedis/prifi_archive#3]
I started working on time stamping, and I wanted to make some notes and ask some questions.

Note: I am adding my code on the coco branch because the coco branch hasn't yet been integrated in master and I wanted access to the 'connection' interface and structures. Creating a timestamp branch on the coco branch could lead to some headaches when merging coco in master. I am open to suggestions, though.

Question 1: In the coco paper, commit section, we say that we *combine" Vi, Vi_hat, our log contribution for this round and the roots of our children's Merkle trees. Does combine here translate to calling Write() on a Cipher?

Question 2 (related to Question 1): Ultimately we want to have these binary Merkle trees that will make it easy for us to prove things like beforeness. It seems that in tree/merkle.go MerkleGet we have the 2 concatenated hashes of the 2 kids kept in their parent. It is not very clear to me if I should have _both_ this blob of two concatenated hashes, _and_ the hash/"combination" of (Vi,Vi_hat, log entry, 2 Merkle roots) stored in a server node for each round. I think I should, because otherwise I would have to somehow pull  Vi, Vi_hat and the log entry from the hash to be able to look at the 2 kids' Merkle roots, but I wanted to check with you guys.

**Comment by bford** [comment]
I just merged the current coco branch into the mainline.  Since the contents of the prifi repo is still extremely preliminary and unstable anyway, feel free just to go ahead and merge the coco branch into the mainline yourselves for now whenever it proves convenient to do so, at least as long as your changes are mainly confined to directories/packages you currently have "exclusive ownership" of.  I don't want to let an attempt at overly-systematized workflow get in the way of progress.

Q1: I think my intent there was just to (say) protobuf-format all of those items into a flat binary blob, and use that as the log entry L_i.  However, there are subtleties...

Q2: Good question; that's one of the design subtleties, which I hadn't gotten around to explaining yet - so let me try now. :)  

The idea behind the binary Merkle tree design in that module is that we want "beforeness proofs" to be both as compact as reasonably feasible, and as generic (independent of particular application) as possible.  

To make them compact, the design uses the trick of storing only one of the two children at each level in the tree, given that the other child can always be constructed (and because the children are always sorted, i.e., order indepenendent, it doesn't matter which one you have; you can always get the other one and reconstruct the two-child Merkle tree node).  

To make the beforeness proof mechanism generic, we don't want it to have to "know about" anything but these primitive hash-chains through binary Merkle trees.  In particular, if there are higher-level formatted objects involved in a system using these beforeness proofs - such as the serialized log-entries mentioned above - we'd rather not have the primitive beforeness-proof method "know" or "care" about the format of log entries.  This is a problem if the log entry seems to be "on the path" from some prior event (say an event timestamped by a client of a particular server within a particular time-step) to some later, dependent event (say the top-level of the root node's master Merkle tree for that tilmestep, which is supposed to aggregate the Merkle trees of all its descendants for that tilmestep).  In other words, we could create a "beforeness proof" that the prior-event-of-interest happened before the child's log entry L_i, and we could create a separate beforeness proof that the log entry happened before (i.e., was referenced by) the root node's Merkle tree for that tilmestep - but if the log entry itself is directly "on" that path, then verifying that complete Merkle proof would require knowing the format of and parsing log entries, which are much bigger than just binary Merkle tree nodes and conceptually operate at a different abstraction level in the system.

So the solution I have in mind is this.  Suppose a "formatted binary blob" contains one or more Merkle tree roots - say R1,...,Rn where n are the number of children whose Merkle tree roots are listed in the blob.  For each of those child Merkle tree roots Rj, we now create one higher-level binary Merkle tree node R'j containing (exactly) two children in the usual binary Merkle tree format: (a) Rj, and (b) the hash H(Li) of the binary blob (e.g., log entry Li) containing the semantically richer content referring to Rj.  This new R'j, now, can be used as the root of a new Merkle (sub-)tree to be embedded in any larger binary Merkle tree for whatever purpose.  

When R'j gets embedded in a larger Merkle tree this way - e.g., the root node's master Merkle tree for this time-step - we can now create either: (a) beforeness proofs or Merkle paths referring to the child's log entry itself H(Li), or (b) beforeness proofs that effectively "bypass" the log-entry by descending through R'j to Rj and on into (and through) any desired path through the child's Merkle sub-tree.

In essence, this slightly weird design, where we add one extra binary Merkle "node" whenever we incorporate a semantic blob such as a log-entry into the Merkle tree, we get the ability both to refer to that binary blob (and prove beforeness relationships involving it) and to bypass that blob in compositions of beforeness proofs involving path components that happened both before and after that binary blob (e.g., path components that the log-entry referred to and path components that indirectly refer to the log-entry).

Does this make any sense?  (If not, feel free to do whatever seems natural for now and we can discuss it further when we have a whiteboard available; that would make it easier.)

Cheers
Bryan

**Comment by iuliatamas** [comment]
We have a pull request in for what we've done for Time Stamping so far.
I expect we'll get some feedback on that, but I also have some questions/ notes.
1. When generating Merkle Trees based on the messages gathered by a server in a round, if the number of messages is not a power of 2 we could: add empty leaves until we reach a power of 2 OR have something like: of the 3 leaves, 1 and 2 form H(12); 3 and H(12) form root. I chose the first because it was easier (based on the code that we already had) and cleaner, but I can change it to the second option.
2. The client now holds a _single_ history of replies received for requests based on the requests' sequence numbers. I was wondering whether we wanted to hold separate sequence numbers and histories for different kinds of requests. I don't think we would need to store the other kinds of request replies in our history, but wanted to check before moving to accommodating more kinds of messages.
3. I currently have the client keep track of the number of rounds it participated in (as perceived by it). Don't know if it's very useful in general, but it helped me make sure the groups of messages are processed in separate rounds on the server side. 

Thank you

**Comment by bford** [comment]
1. I don't have a strong preference on this; the second approach would of course produce slightly more efficient trees, but I'm not sure it's worth worrying about for now.  (It actually doesn't affect the "protocol" at all so it's an optimization we can easily leave out for now and silently add in later without affecting anything else.)
2. I have no real preference on this either at the moment; for now just do what seems simplest to you.  Since the client's request sequence number should presumably completely opaque and uninterpreted by the server, this is probably another thing the protocol doesn't even really care about or need to specify; some clients could in principle work one way while other clients work the other.
3. Sure, maintaining useful statistics/counters is generally never a bad idea!

B

**Comment by bford** [comment]
@iuliatamas is anything still outstanding wrt this issue?  If not can you close it?  Thanks.
